{
  "options": {
    "nickName": "家人亲戚",
    "avatar": "http://wx2.sinaimg.cn/thumb150/4d6e3e3bgy1fk3yx2hfmzj21jk2bce83.jpg",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=001vBzhR19LKRQ",
    "bgMusicName": "《时间都去哪儿了》",
    "loadingTxt": "耐心等候，美好即将开启～",
    "shareTitle": "$nickname分享了一个相册",
    "shareBtnTxt": "微信分享",
    "hideCatBtn": false,
    "hideContactBtn": false
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/mw690/4d6e3e3bgy1fk3yx2hfmzj21jk2bce83.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "龟山公园合影",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx4.sinaimg.cn/mw690/4d6e3e3bgy1fj5h71uv54j20pj0zugpz.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "外婆和二姨",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj5hqjaks9j20k00zk0w3.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "大舅",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5j515bt3j20qo0zkwg0.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "表姐和孩子",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fom5tuhiecj20np0hsgml.jpg",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "帅气表哥",
    "text2": ""
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5jdwuyalj20qo0zkju5.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "老爸和姐姐",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6k5795j20fm0ku0wa.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "五姐妹",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6qjlwjj20et0irq71.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "老妈和三姨",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6i3s2fj20ku0fm782.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "姐和表妹",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5hq7q484g20a00hsb2b.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "湘湘动画",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5jdx8xdhj20qo0qo0uf.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "二姨和啊婕",
    "text2": "依然要望着彼此温柔地傻笑"
  },{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6nq03rj20ir0p0773.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "三姨和姨丈",
    "text2": "哪怕颠沛，哪怕流离……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h737feaj20qo0zkwg8.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "三姨和表弟",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fk43jap16oj20k00zkqdt.jpg",
    "posterUrl": "https://wx4.sinaimg.cn/large/4d6e3e3bly1g9ct0mealnj20y30j6tjo.jpg",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "大进2017",
    "text2": "幸福像花儿一样绽放"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fk3yy6yjlgj21yi2zyhdt.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "表弟",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj5h729zpwj20pg0yw42g.jpg",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "四姨和阿秀",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fk3yxv8y3qj21qi2bchdv.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "小舅舅和舅妈",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6mqo6gj20ir0p0tbo.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "表弟",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj5h6r2z6zj20lx12w19c.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "小姨夫妇",
    "text2": "连狂风暴雨都变得温柔甜蜜……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fk3yx2hfmzj21jk2bce83.jpg?v=2",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "佛",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx",
    "swiperItmeClass": "bp-top"
  }]
}