{
  "options": {
    "nickName": "楚乔传",
    "avatar": "http://wx2.sinaimg.cn/thumb150/4d6e3e3bgy1fjbcehngnwj209d0gn0t9.jpg",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=003uB0Lh0pexs8",
    "bgMusicName": "《望》",
    "loadingTxt": "即将上映，请耐心等候～",
    "shareTitle": "《楚乔传》剧照，速来围观!",
    "shareBtnTxt": "召唤颖火虫",
    "shareSuccTip": "可以分享啦 ^_-"
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbcehngnwj209d0gn0t9.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "卡通四人",
    "text2": "哪怕颠沛，哪怕流离……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbceeubfdj20fo0ruwg2.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "宇文玥看楚乔",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbcefljefj20fo0nhwgf.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "十四",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbcelbyguj20fo0rt77q.jpg",
    "textBottom": "100rpx",
    "textLeft": "34rpx",
    "text": "公主悔婚"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbceijengj20fo0ru0vi.jpg",
    "textBottom": "374rpx",
    "textLeft": "14rpx",
    "text": "公主倒地",
    "text2": "留下我们的足迹 老了好翻着照片回忆……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbcegnnp3j20fo0ruwfv.jpg",
    "textBottom": "100rpx",
    "textLeft": "74rpx",
    "text": "公主求燕洵",
    "text2": "就像棉花糖一样 软软甜甜",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbcekkyesj20fo0rjabu.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "公主抱魏",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbcejet7ij20bd0evjs2.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "李策",
    "text2": "依然要望着彼此温柔地傻笑",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjbclvmlcog20ia0abhe0.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "墨儿呛水干爹",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbce86id3j20fo0rvq53.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "公子和墨儿",
    "text2": "摇曳着两个相互依偎的倒影……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjbclto2rmg207d046hdu.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "摸手",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbce77v1vj20fo0rumyv.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "公子背墨儿战斗",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbcednv8aj20fo0ru3zw.jpg",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "楚乔燕洵",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbce7odotj20fo0y0mzi.jpg",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "楚乔燕洵片花",
    "text2": "幸福像花儿一样绽放",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbce6uslqj20fo0nimz0.jpg",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "公主红衣",
    "text2": ""
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjbclydszbg20dw05ux6q.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "熊抱",
    "text2": "把时光定格在七彩泡泡里……"
  }]
}