{
  "options": {
    "nickName": "楚乔传剧情",
    "avatar": "http://wx2.sinaimg.cn/thumb150/4d6e3e3bgy1fjb7kqix3kj20fo0nb0ub.jpg",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=001Gcvmw1mDgTT",
    "bgMusicName": "《学不会》／／202908086",
    "loadingTxt": "即将上映，请耐心等候～",
    "shareTitle": "《楚乔传》剧照，快来围观!",
    "shareBtnTxt": "召唤颖火虫",
    "shareSuccTip": "可以分享啦 ^_-"
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7kqix3kj20fo0nb0ub.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "人猎",
    "text2": "哪怕颠沛，哪怕流离……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7ks6tu5j20fo0rv400.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "世子",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjb7kr9bebj20fo0wr77l.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "世子策马",
    "text2": "依然要望着彼此温柔地傻笑",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjb7kmcroej20fo0tsgnu.jpg",
    "textBottom": "100rpx",
    "textLeft": "34rpx",
    "text": "九幽台宇文玥",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7kjmownj20ek0qoq4h.jpg",
    "textBottom": "374rpx",
    "textLeft": "14rpx",
    "text": "九幽台 燕浔 白笙",
    "text2": "留下我们的足迹 老了好翻着照片回忆……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjb7kw0nw0j20eg0i0jsj.jpg",
    "textBottom": "100rpx",
    "textLeft": "74rpx",
    "text": "天牢",
    "text2": "就像棉花糖一样 软软甜甜"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7kkr4abj20fo0q8wgb.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "反制",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjb7kt4q6pj20fo0q876e.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "陷害魏",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7ktjg0wj20fo0q8407.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "陷害魏2",
    "text2": "摇曳着两个相互依偎的倒影……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7ko0haaj20dw0najt5.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "李策献花",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjb7kne2wqj20dw0nadhb.jpg",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "李策丛林",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7kon984j20fo0q8taz.jpg",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "李策宇文玥",
    "text2": "幸福像花儿一样绽放"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjb7kvi7bfj20fo0q8abz.jpg",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "惹楚乔炸毛",
    "text2": ""
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7klcofxj20fo0v9goa.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "公主悔婚",
    "text2": "把时光定格在七彩泡泡里……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kkddvuj20fo0radie.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "带你们回家",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7ksntmgj20fo0q9dik.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "浴房春潮",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7krsz88j20fo0v9adb.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "吃烧饼",
    "text2": "把时光定格在七彩泡泡里……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kmsye2j20fo0v9tay.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "汴唐李策",
    "text2": "把时光定格在七彩泡泡里……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kwctcxj20fo0jzq4l.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "熊抱",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kpxs8wj20fo0qfgop.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "强吻6",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kp9wguj20fo0qfjth.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "强吻3",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7klubioj20fo0qfq4m.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "纠结",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjb7kjzwoyj20fo0kw75x.jpg",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "冰湖",
    "text2": "把时光定格在七彩泡泡里……"
  }]
}