{
  "options": {
    "nickName": "燕洵",
    "avatar": "http://wx2.sinaimg.cn/thumb150/4d6e3e3bgy1fjbbucvshvj20fo0ruq51.jpg",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=000IDtgp2vMWgD",
    "bgMusicName": "《因为一个人》",
    "loadingTxt": "即将上映，请耐心等候～",
    "shareTitle": "《楚乔传》燕洵剧照，快来围观!",
    "shareBtnTxt": "召唤柿子粉",
    "shareSuccTip": "可以分享啦 ^_-"
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbucvshvj20fo0ruq51.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "精致的胡闹",
    "text2": "哪怕颠沛，哪怕流离……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbu7kqi1j20fo0rujtr.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "别怕有我在呢",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbbu6opeej20fo0rujt7.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "岂不很没面子",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbbu9lgj3j20fo0ru3zt.jpg",
    "textBottom": "100rpx",
    "textLeft": "34rpx",
    "text": "雪地"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbua4jmmj20fo0nita4.jpg",
    "textBottom": "374rpx",
    "textLeft": "14rpx",
    "text": "雪地2",
    "text2": "留下我们的足迹 老了好翻着照片回忆……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbbubmz46j20f00qo760.jpg",
    "textBottom": "100rpx",
    "textLeft": "74rpx",
    "text": "百倍奉还",
    "text2": "就像棉花糖一样 软软甜甜"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbudu1apj20dc0npdge.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "白衣注视",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbbuf49rxj20fo0rvabk.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "黑衣注视",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbuc9f7yj20fo0rkad7.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "马上铠甲",
    "text2": "摇曳着两个相互依偎的倒影……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbuehiyrj20fo0ru761.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "燕临天下",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjbbu8hiocj20fo0mmmz0.jpg",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "紫色衣服",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbuaok8xj20f10qojs3.jpg",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "黑衣帽",
    "text2": "幸福像花儿一样绽放"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjbbu73iq1j20fo0rkdiv.gif",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "红袍",
    "text2": ""
  }]
}