{
  "options": {
    "nickName": "性感赵小兔",
    "avatar": "http://wx1.sinaimg.cn/sq612/4d6e3e3bgy1fj7t9nni0mg206s06skjl.gif",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=0003t6PH1mjYtS",
    "bgMusicName": "《get back again ASAP",
    "loadingTxt": "耐心等候～心急吃不了…",
    "shareTitle": "原来赵小兔性感起来是酱紫哒!",
    "shareBtnTxt": "召唤狼友",
    "shareSuccTip": "可以分享啦 ^_-"
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7vty89s5j20ly0y310f.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "手杖1",
    "text2": "哪怕颠沛，哪怕流离……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj7vyfpuqcj20ly0y378c.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "2",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7vtxplr3j20ly0y3n0u.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "3",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj7vtwiy9xj20ly0y3whm.jpg",
    "textBottom": "100rpx",
    "textLeft": "34rpx",
    "text": "4",
    "text2": ""
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7t9feprjj20lc0zkade.jpg",
    "textBottom": "374rpx",
    "textLeft": "14rpx",
    "text": "剪刀",
    "text2": "留下我们的足迹 老了好翻着照片回忆……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj7vtvsrsxj20ly0y3nbz.jpg",
    "textBottom": "100rpx",
    "textLeft": "74rpx",
    "text": "可乐",
    "text2": "就像棉花糖一样 软软甜甜"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7uwjk4gwj20ly0y341x.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "吹泡泡",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj7uk7a1b7j20ly0y3gw6.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "凳子吹泡泡",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7vtx3tpcj20ly0y3789.jpg",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "拎包",
    "text2": "摇曳着两个相互依偎的倒影……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7t9kxuedj20hs0vk7bb.jpg",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "亲亲",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fj7t9k9fgfj20nt0xcacf.jpg",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "礼服",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7t9gf6r9j20qe1axn5k.jpg",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "牛奶服",
    "text2": "幸福像花儿一样绽放"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fj7t9lomwcg206s06sh9g.gif",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "动画1",
    "text2": ""
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fj7t9nni0mg206s06skjl.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "动画2",
    "text2": "把时光定格在七彩泡泡里……"
  }]
}