{
  "options": {
    "nickName": "吃吃吃",
    "avatar": "http://wx4.sinaimg.cn/sq612/4d6e3e3bgy1fjfonz5tzgj20dc0nqq9o.jpg",
    "bgMusic": "https://api.qq.jsososo.com/song/url?isRedirect=1&id=004BlvsX1ecuHy",
    "bgMusicName": "《洛天依投食歌》",
    "loadingTxt": "耐心等候～心急吃不了…",
    "shareTitle": "围观吃货一枚!",
    "shareBtnTxt": "召唤好友",
    "shareSuccTip": "可以分享啦 ^_-"
  },
  "swiperList": [{
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfonz5tzgj20dc0nqq9o.jpg",
    "textClass": "fadeInUp",
    "textBottom": "100rpx",
    "textLeft": "114rpx",
    "text": "花千骨",
    "text2": "哪怕颠沛，哪怕流离……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjkc9zh0gkg206s07f4po.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "花千骨 当然好吃",
    "text2": "依然要望着彼此温柔地傻笑"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjfoq1ucoug204b05kajo.gif",
    "textBottom": "100rpx",
    "textLeft": "34rpx",
    "text": "花千骨吐",
    "text2": ""
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfoprizswg206l07nb29.gif",
    "textBottom": "374rpx",
    "textLeft": "14rpx",
    "text": "花千骨烧饼",
    "text2": "留下我们的足迹 老了好翻着照片回忆……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfoqj7147g2099088x6p.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "花千骨－包子",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjfoq3eoobg205406l49o.gif",
    "textBottom": "100rpx",
    "textLeft": "74rpx",
    "text": "杉杉蛋糕",
    "text2": "就像棉花糖一样 软软甜甜"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfoq18bcog205x096kjl.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "杉杉－水果",
    "text2": "摇曳着两个相互依偎的倒影……"
  }, {
    "url": "http://wx3.sinaimg.cn/large/4d6e3e3bgy1fjfoo4ptt7g20670a61kx.gif",
    "textBottom": "40rpx",
    "textLeft": "54rpx",
    "text2Left": "57rpx",
    "text": "杉杉－水果2",
    "text2": "我说我喜欢你软软的小手"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfopu8fjqg205q075npe.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "杉杉捂脸",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfopp7lq5g206h05ravz.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "杉杉吃面",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfopv8v1wg205806nwv5.gif",
    "textBottom": "0",
    "textLeft": "54rpx",
    "text2Left": "117rpx",
    "text": "杉杉－工伤",
    "text2": "幸福像花儿一样绽放"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfoq2o7dwg204l05d1kx.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text": "楚乔传 刺啊",
    "text2": "我踮起脚尖听你凑上来的小秘密"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfooca8xug205j07kk5g.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "楚乔传苹果",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfopk1z46g205r06y4qp.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "军装－递包子",
    "text2": "把时光定格在七彩泡泡里……",
    "swiperItmeClass": "bp-top"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfopmn4nng204j05lu0x.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "长沙",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfopxfyfeg204r061gw2.gif",
    "textBottom": "40rpx",
    "textLeft": "34rpx",
    "text2Left": "100rpx",
    "text": "综艺 红衣",
    "text2": "这样的午后，适合梦见你"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfoo0qfubg209r0d0hdt.gif",
    "textBottom": "234rpx",
    "textLeft": "126rpx",
    "text": "综艺－吓",
    "text2": ""
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfopkssrsg204b06149e.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "综艺－拉手",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfoocy2sdg204k061n5u.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "综艺－再吃一口",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfoo8hmx8g207x09m4qp.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "综艺下饭",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfonzlcmij20dc0jc772.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "综艺男神",
    "text2": "把时光定格在七彩泡泡里……"
  }, {
    "url": "http://wx4.sinaimg.cn/large/4d6e3e3bgy1fjfopwfwufg204e050qdt.gif",
    "textBottom": "77rpx",
    "textLeft": "114rpx",
    "text": "综艺－好吃",
    "text2": "我给你撑起另一片天空",
    "text2Left": "140rpx"
  }, {
    "url": "http://wx1.sinaimg.cn/large/4d6e3e3bgy1fjfony5kwdg208m08mh2z.gif",
    "textClass": "fadeInUp",
    "textBottom": "87rpx",
    "textLeft": "54rpx",
    "text2Left": "70rpx",
    "text": "综艺吃不饱",
    "text2": "把时光定格在七彩泡泡里……"
  }]
}